$ErrorActionPreference = "Stop"

$script_dir = Split-Path -Parent $MyInvocation.MyCommand.Path

$root = Split-Path -Parent $script_dir

$source = Join-Path $env:WINDIR "System32\d3d11.dll"

$out_file = Join-Path $root "src\proxy\exports.g.h"

$names = @()

try
{
    $dump = & dumpbin /nologo /exports "$source"

    $in_table = $false

    foreach ($line in $dump)
    {
        if ($line -match "^\s+ordinal\s+hint\s+RVA\s+name")
        {
            $in_table = $true

            continue
        }

        if (-not $in_table)
        {
            continue
        }

        if ($line -match "^\s+\d+\s+[0-9A-Fa-f]+\s+(?:[0-9A-Fa-f]{8}\s+)?([A-Za-z_][A-Za-z0-9_]*)")
        {
            $names += $Matches[1]
        }
    }
}
catch
{
    $names = @()
}

if ($names.Count -eq 0)
{
    $names = @("D3D11CreateDevice", "D3D11CreateDeviceAndSwapChain", "D3D11CoreCreateDevice", "D3D11CoreCreateLayeredDevice", "D3D11CoreGetLayeredDeviceSize", "D3D11CoreRegisterLayers", "D3D11On12CreateDevice")

    Write-Host "gen_proxy: dumpbin parse failed, using minimal fallback set"
}

$names = $names | Select-Object -Unique

$no_ext = $source -replace "\.dll$", ""

$forward = $no_ext -replace "\\", "\\"

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("#pragma once")

[void]$sb.AppendLine("")

[void]$sb.AppendLine("// generated by tools/gen_proxy.ps1 - forwards every d3d11 export to the real system dll")

[void]$sb.AppendLine("// do not edit by hand, regenerated on every build")

[void]$sb.AppendLine("")

foreach ($n in $names)
{
    [void]$sb.AppendLine("#pragma comment(linker, `"/export:$n=$forward.$n`")")
}

$out_dir = Split-Path -Parent $out_file

if (-not (Test-Path $out_dir))
{
    New-Item -ItemType Directory -Path $out_dir | Out-Null
}

Set-Content -Path $out_file -Value $sb.ToString() -Encoding ASCII

Write-Host ("gen_proxy: wrote {0} forwarders -> {1}" -f $names.Count, $out_file)
